# fly.toml app configuration file generated for mon-scrapeur on 2025-03-10T01:07:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mon-scrapeur'
primary_region = 'cdg'

[build]

[http_service]
internal_port = 5000  # Assure que Fly.io mappe bien le port 5000
force_https = true
auto_stop_machines = false  # Empêche l'arrêt automatique
auto_start_machines = true
min_machines_running = 1  # Garde une machine toujours active
processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
